apiVersion: apps/v1
kind: Deployment
metadata:
 name: Train-Schedule
spec:
 replicas: 2
 template:
  metadata:
   labels:
    app: ab
  spec:
   containers:
   - name: train_schedule
     image: sagjayar/ab:latest
     ports:
     - containerPort: 8080
     env: 
     - name: ALLOW_EMPTY_PASSWORD
       value: "yes"
 selector:
  matchLabels:
   app: ab
